namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_ALGOLIA_APP_ID: string;
    NEXT_PUBLIC_ALGOLIA_ADMIN_API_KEY: string;
    NEXT_PUBLIC_ALGOLIA_INDEX_NAME: string;

    NEXT_PUBLIC_PRODUCT_CONSUMER_KEY: string;
    NEXT_PUBLIC_PRODUCT_CONSUMER_SECRET: string;

    NEXT_PUBLIC_MAILJET_API_KEY: string;
    NEXT_PUBLIC_MAILJET_SECRET_KEY: string;
    NEXT_PUBLIC_CONTACT_US_EMAIL: string;

    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;
    RECAPTCHA_SECRET_KEY: string;
  }
}
